# Generated by Django 3.2.4 on 2022-05-03 19:44

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('purpose', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=projects.models.image_folder)),
                ('file', models.FileField(blank=True, upload_to=projects.models.project_folder)),
            ],
        ),
    ]
