# Generated by Django 3.2.4 on 2022-05-10 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='Feedback',
        ),
    ]
