# Generated by Django 3.2.4 on 2022-05-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.FileField(upload_to='')),
                ('impulse', models.FileField(upload_to='')),
                ('result', models.FileField(upload_to='')),
            ],
        ),
    ]
